services:
    crm.contact:
        class: Librinfo\CRMBundle\Admin\ContactAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\Contact, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.contact_admin.label
                label_translator_strategy: librinfo_core.label.strategy.librinfo

    crm.organism:
        class: Librinfo\CRMBundle\Admin\OrganismAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\Organism, LibrinfoCRMBundle:OrganismAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.organism_admin.label
                label_translator_strategy: librinfo_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [edit, LibrinfoCRMBundle:OrganismAdmin:edit.html.twig]]

    crm.organismphone:
        class: Librinfo\CRMBundle\Admin\OrganismPhoneAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\OrganismPhone, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.organism_phone_admin.label
                label_translator_strategy: librinfo_core.label.strategy.librinfo

    crm.category:
        class: Librinfo\CRMBundle\Admin\CategoryAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\Category, LibrinfoBaseEntitiesBundle:TreeableCRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.category_admin.label
                label_translator_strategy: librinfo_core.label.strategy.librinfo

    crm.role:
        class: Librinfo\CRMBundle\Admin\RoleAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\Role, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.role_admin.label
                label_translator_strategy: librinfo_core.label.strategy.librinfo

    crm.contactgroup:
        class: Librinfo\CRMBundle\Admin\ContactGroupAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\ContactGroup, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.contact_group_admin.label
                label_translator_strategy: librinfo_core.label.strategy.librinfo

    crm.contactphone:
        class: Librinfo\CRMBundle\Admin\ContactPhoneAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\ContactPhone, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.contact_phone_admin.label
                label_translator_strategy: librinfo_core.label.strategy.librinfo

    crm.circle:
        class: Librinfo\CRMBundle\Admin\CircleAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\Circle, LibrinfoCRMBundle:CircleAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.circle_admin.label
                label_translator_strategy: librinfo_core.label.strategy.librinfo

    crm.position:
        class: Librinfo\CRMBundle\Admin\PositionAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\Position, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.position_admin.label
                label_translator_strategy: librinfo_core.label.strategy.librinfo

    crm.position_type:
        class: Librinfo\CRMBundle\Admin\PositionTypeAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\PositionType, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.position_type_admin.label
                label_translator_strategy: librinfo_core.label.strategy.librinfo

    crm.phone_type:
        class: Librinfo\CRMBundle\Admin\PhoneTypeAdminConcrete
        arguments: [~, Librinfo\CRMBundle\Entity\PhoneType, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.phone_type_admin.label
                label_translator_strategy: librinfo_core.label.strategy.librinfo
