services:

    security.access.circle_voter:
        class:      Sil\Bundle\CRMBundle\Security\Authorization\Voter\CircleVoter
        public:     false
        tags:
            - { name: security.voter }

    # sonata.admin.exporter:
    #     class: Sil\Bundle\CRMBundle\Admin\Exporter
    #     calls:
    #         - [setTokenStorage, ['@security.token_storage']]
    #         - [setTranslator, ['@translator']]
    #         - [setTwig, ['@twig']]
    #         - [setRouter, ['@router']]

    # repository as a service
    sil_crm.repository.circle:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine', getRepository]
        arguments:
            - Sil\Bundle\CRMBundle\Entity\Circle

    sil_crm.app_circles:
        class: Sil\Bundle\CRMBundle\Services\AppCirclesService
        arguments: ['@sil_crm.repository.circle']

# ENTITY CODE GENERATORS

    sil_crm.code_generator.supplier:
        class: Sil\Bundle\VarietyBundle\CodeGenerator\SupplierCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%sil_crm.code_generator.supplier%', '@doctrine.orm.entity_manager', '%sil.model.crm_organism.class%']
        tags:
            - { name: blast.entity_code_generator }

    sil_crm.code_generator.customer:
        class: Sil\Bundle\VarietyBundle\CodeGenerator\CustomerCodeGenerator
        factory:   ['@blast_core.code_generator_factory', create]
        arguments: ['%sil_crm.code_generator.customer%', '@doctrine.orm.entity_manager', '%sil.model.crm_organism.class%']
        tags:
            - { name: blast.entity_code_generator }

### FORM TYPES ###

    sil_crm.form.type.zipcity:
        class: Sil\Bundle\CRMBundle\Form\Type\ZipCityType
        tags:
            - { name: form.type, alias: sil_zip_city }

    sil_crm.form.type.main_address:
        class: Sil\Bundle\CRMBundle\Form\Type\MainAddressType
        tags:
            - { name: form.type, alias: sil_main_address }

    sil_crm.form.type.main_phone:
        class: Sil\Bundle\CRMBundle\Form\Type\MainPhoneType
        tags:
            - { name: form.type, alias: sil_main_phone }

    sil_crm.form.type.fake_email:
        class: Sil\Bundle\CRMBundle\Form\Type\FakeEmailType
        tags:
            - { name: form.type, alias: sil_fake_email }

### BLAST CALLBACKS ###
    sil.crm.filters.customer:
        class: Sil\Bundle\CRMBundle\Services\Filters\OrganismFilter
